export const AUTH_REQUEST_LOGIN = 'AUTH_REQUEST_LOGIN';
export const AUTH_RESPONSE_LOGIN = 'AUTH_RESPONSE_LOGIN';
export const AUTH_REQUEST_REGISTER = 'AUTH_REQUEST_REGISTER';
export const AUTH_RESPONSE_REGISTER = 'AUTH_RESPONSE_REGISTER';
export const AUTH_REQUEST_EMAIL_ACTIVATION = 'AUTH_REQUEST_EMAIL_ACTIVATION';
export const AUTH_RESPONSE_EMAIL_ACTIVATION = 'AUTH_RESPONSE_EMAIL_ACTIVATION';

export const AUTH_REQUEST_LOGOUT = 'AUTH_REQUEST_LOGOUT';

export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
