export const REQUEST_GET_AIRPORT_LIST = 'REQUEST_GET_AIRPORT_LIST';
export const RESPONSE_GET_AIRPORT_LIST = 'RESPONSE_GET_AIRPORT_LIST';

export const REQUEST_GET_AIRPORT_ITEM = 'REQUEST_GET_AIRPORT_ITEM';
export const RESPONSE_GET_AIRPORT_ITEM = 'RESPONSE_GET_AIRPORT_ITEM';
